name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: List files
      run: |
        ls -la
        ls -la frm/

    - name: Show commit and workflow file
      run: |
        echo "Commit SHA: $GITHUB_SHA"
        cat .github/workflows/python-publish.yml
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '>=3.11'

    - name: Clean dist folder
      run: rm -rf dist/

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
        pip install twine
        pip install hatchling
  
    - name: Build package
      run: python -m build --no-isolation --verbose

    - name: Publish package
      env:
        TWINE_USERNAME: '__token__'
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: twine upload dist/*
